<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="marvin" name="com.marvinformatics.kissthrow.ThrowsTest" tests="4" failures="3" timestamp="24 Aug 2012 13:37:10 GMT" time="0.038" errors="0">
  <testcase name="silentThrowThrowable" time="0.001" classname="com.marvinformatics.kissthrow.ThrowsTest"/>
  <testcase name="silentThrowException" time="0.016" classname="com.marvinformatics.kissthrow.ThrowsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.Exception but got org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.Exception but got org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowException(ThrowsTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
    </failure>
  </testcase> <!-- silentThrowException -->
  <testcase name="silentThrowIOException" time="0.001" classname="com.marvinformatics.kissthrow.ThrowsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.io.IOException but got org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
">
      <![CDATA[org.testng.TestException: 
Expected exception java.io.IOException but got org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowIOException(ThrowsTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
    </failure>
  </testcase> <!-- silentThrowIOException -->
  <testcase name="silentThrowRuntimeException" time="0.020" classname="com.marvinformatics.kissthrow.ThrowsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowRuntimeException(ThrowsTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
    </failure>
  </testcase> <!-- silentThrowRuntimeException -->
</testsuite> <!-- com.marvinformatics.kissthrow.ThrowsTest -->
